language: c
script:
  - make -s check
  - make -s badge


branches:
  only:
    - badge

install:
 - git clone --depth=1 https://github.com/LCTT/lctt-scripts
 - sed -i "/ProjectRoot=/cProjectRoot=$(pwd)" ./lctt-scripts/lctt.cfg

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: badge
